import React, { useState } from 'react';
import { Book, ChevronRight, DollarSign, TrendingUp, Wallet, ArrowRightLeft, Lock, Shield, Info } from 'lucide-react';

interface ConceptSection {
  id: string;
  title: string;
  icon: React.ReactNode;
  content: React.ReactNode;
}

export function Documentation() {
  const [activeSection, setActiveSection] = useState<string | null>(null);

  const sections: ConceptSection[] = [
    {
      id: 'what-are-lsts',
      title: ' Staking Tokens (LSTs)?',
      icon: <Lock className="w-6 h-6 text-blue-500" />,
      content: (
        <div className="space-y-4">
          <p className='text-black dark:text-white'>
            Liquid Staking Tokens (LSTs) are digital assets that represent staked cryptocurrency while allowing you to maintain liquidity. Think of them like a "receipt" for your staked assets.
          </p>
          <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg">
            <h4 className="font-medium text-blue-700 dark:text-blue-300 mb-2">Real-world Example:</h4>
            <p className='text-black dark:text-white'>
              Imagine you deposit $1,000 worth of ETH into Lido. You'll receive stETH tokens worth $1,000 in return. While your original ETH is being staked and earning rewards, you can use your stETH for other purposes like trading or providing liquidity.
            </p>
          </div>
        </div>
      )
    },
    {
      id: 'how-it-works',
      title: 'How Does Liquid Staking Work?',
      icon: <ArrowRightLeft className="w-6 h-6 text-green-500" />,
      content: (
        <div className="space-y-4">
          <p className='text-black dark:text-white'>
            Liquid staking protocols allow you to stake your assets while receiving a liquid token in return. These tokens automatically accrue staking rewards.
          </p>
          <div className="bg-gray-50 text-black dark:bg-gray-800 p-4  rounded-lg text-white">
            <h4 className="font-medium mb-2">The Process:</h4>
            <ol className="list-decimal list-inside space-y-2">
              <li>You deposit ETH into a liquid staking protocol</li>
              <li>You receive LSTs (like stETH) in return</li>
              <li>Your staked ETH earns staking rewards</li>
              <li>Your LST balance increases automatically to reflect rewards</li>
            </ol>
          </div>
        </div>
      )
    },

    {
      id: 'key-metrics',
      title: 'Understanding Key Metrics',
      icon: <TrendingUp className="w-6 h-6 text-purple-500" />,
      content: (
        <div className="space-y-6">
          <div>
            <h4 className="font-medium text-gray-900 dark:text-white mb-2">TVL (Total Value Locked)</h4>
            <p className="mb-2 text-white">The total value of assets staked in a protocol.</p>
            <div className="bg-purple-50 dark:bg-purple-900/20 text-white p-4 rounded-lg">
              <p className="text-sm text-black dark:text-white">
                Example: If Lido has a TVL of $10B, it means users have staked $10B worth of assets through their platform.
              </p>
            </div>
          </div>

          <div>
            <h4 className="font-medium text-gray-900 dark:text-white mb-2">APY (Annual Percentage Yield)</h4>
            <p className="mb-2 text-white">The yearly return rate on your staked assets, including compound interest.</p>
            <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg">
              <p className="text-sm text-black dark:text-white">
                Example: A 5% APY means $1,000 staked would earn approximately $50 in a year if rates remain constant.
              </p>
            </div>
          </div>

          <div>
            <h4 className="font-medium text-gray-900 dark:text-white mb-2">Protocol Revenue</h4>
            <p className="mb-2 text-white">Income generated by the protocol through fees and other sources.</p>
            <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg">
              <p className="text-sm text-black dark:text-white">
                Example: If a protocol charges 10% of staking rewards and validators earn $1M, the protocol revenue would be $100K.
              </p>
            </div>
          </div>
        </div>
      )
    },
    {
      id: 'risks',
      title: 'Understanding Risks',
      icon: <Shield className="w-6 h-6 text-red-500" />,
      content: (
        <div className="space-y-4">
          <p className='text-black dark:text-white'>
            While liquid staking offers many benefits, it's important to understand the associated risks:
          </p>
          <div className="grid gap-4">
            <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
              <h4 className="font-medium text-red-700 dark:text-red-300 mb-2">Smart Contract Risk</h4>
              <p className="text-sm text-black dark:text-white">
                LSTs rely on smart contracts which could potentially have vulnerabilities. Always use established protocols with audited contracts.
              </p>
            </div>
            <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
              <h4 className="font-medium text-red-700 dark:text-red-300 mb-2">Validator Risk</h4>
              <p className="text-sm text-black dark:text-white">
                If validators misbehave, they can be slashed, potentially affecting the value of your LSTs.
              </p>
            </div>
            <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
              <h4 className="font-medium text-red-700 dark:text-red-300 mb-2">Market Risk</h4>
              <p className="text-sm text-black dark:text-white">
                LST prices can fluctuate based on market conditions and may trade at a discount to their underlying asset.
              </p>
            </div>
          </div>
        </div>
      )
    },
    {
      id: 'getting-started',
      title: 'Getting Started with LSTs',
      icon: <Wallet className="w-6 h-6 text-indigo-500" />,
      content: (
        <div className="space-y-4 text-black dark:text-white">
          <p>
            Ready to start your liquid staking journey? Here's a step-by-step guide:
          </p>
          <div className="bg-indigo-50 dark:bg-indigo-900/20 p-4 rounded-lg space-y-4">
            <div>
              <h4 className="font-medium text-indigo-700 dark:text-indigo-300 mb-2">1. Choose a Protocol</h4>
              <p className="text-sm">
                Research different protocols based on:
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>Security track record</li>
                  <li>APY rates</li>
                  <li>Fee structure</li>
                  <li>Market liquidity</li>
                </ul>
              </p>
            </div>
            <div>
              <h4 className="font-medium text-indigo-700 dark:text-indigo-300 mb-2">2. Prepare Your Wallet</h4>
              <p className="text-sm">
                Ensure you have:
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>A compatible wallet (e.g., MetaMask)</li>
                  <li>Enough ETH for staking and gas fees</li>
                </ul>
              </p>
            </div>
            <div>
              <h4 className="font-medium text-indigo-700 dark:text-indigo-300 mb-2">3. Start Small</h4>
              <p className="text-sm">
                Begin with a small amount to understand the process before committing larger sums.
              </p>
            </div>
          </div>
        </div>
      )
    }
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          LST Documentation
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          Learn about Liquid Staking Tokens and how to get started
        </p>
      </div>

      <div className="grid md:grid-cols-[300px,1fr] gap-8">
        {/* Sidebar Navigation */}
        <div className="space-y-2">
          {sections.map((section) => (
            <button
              key={section.id}
              onClick={() => setActiveSection(section.id)}
              className={`w-full flex items-center justify-between p-3 rounded-lg text-left transition-colors ${
                activeSection === section.id
                  ? 'bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400'
                  : 'hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
              }`}
            >
              <div className="flex items-center gap-3">
                {section.icon}
                <span className="font-medium">{section.title}</span>
              </div>
              <ChevronRight size={16} className={`transform transition-transform ${
                activeSection === section.id ? 'rotate-90' : ''
              }`} />
            </button>
          ))}
        </div>

        {/* Content Area */}
        <div className="min-h-[500px]">
          {activeSection ? (
            <div className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm border border-gray-200 dark:border-gray-700">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">
                {sections.find(s => s.id === activeSection)?.title}
              </h2>
              {sections.find(s => s.id === activeSection)?.content}
            </div>
          ) : (
            <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-6 flex items-center justify-center">
              <div className="text-center">
                <Info className="w-12 h-12 text-blue-500 mx-auto mb-4" />
                <p className="text-blue-600 dark:text-blue-400">
                  Select a topic from the sidebar to learn more
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}